### ISSUE TITLE
Is this project stoped?

### ISSUE THREAD

**Issue by danleechina** [LukeCarrier/android-governor#7]
I saw the last commit was 6 months ago. It has been quite long. Is it stoped?

**Comment by LukeCarrier** [comment]
I'm afraid I've had other commitments which have kept me from maintaining the project.

If other developers were interested in joining the effort, I'd gladly set aside some time to maintain Governor.

**Comment by danleechina** [comment]
Oh, my graduation project is somehow like this. So maybe I can help this project.

**Comment by danleechina** [comment]
And i saw you used many things like backbone, gulp, underscore, and so on. I even didn't know these things before I read your source. What I know is using Nodejs+Express to develope a website. So the things you used made me feel difficult

**Comment by LukeCarrier** [comment]
All of the tools/libraries you listed above are commonplace and well documented. If you're comfortable with JS, it's fairly easy applying that knowledge:
* [Backbone](http://backbonejs.org/)
* [Gulp](http://gulpjs.com/)
* [Underscore](http://underscorejs.org/)

It would be impractical writing the codebase entirely in JS because we need to use Android's standard library to do anything useful. I'm up for suggestions as to tools and libraries, but I'm really not sure where Node would fit into this project.

**Comment by danleechina** [comment]
Thank you for your advice. I am learning these technologies now.

**Comment by LukeCarrier** [comment]
Awesome! I'm going to close this issue now.

If you're interested in contributing, just go ahead, do some stuff and drop me a pull request. I'll be able to give you pointers to help you get started. :)
